substitutions:
  _IMAGE_NAME: mom-regression-suite-test
  _SERVICE_NAME: mom-regression-suite-test

steps:

# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '.']


 # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']


 # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - '${_SERVICE_NAME}'
   - '--image'
   - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--memory=1Gi'
   - '--port'
   - '8080'
#   - '--allow-unauthenticated'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'auth'
   - 'activate-service-account'
   - 'mom-regression-suite-sa@ce-cxmo-mom-dev-01.iam.gserviceaccount.com'
   - '--key-file'
   - 'mom-regression-suite-sa-key.json'

- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
   - "-c"
   - |
       RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" -H  "Authorization: Bearer $(gcloud auth print-identity-token mom-regression-suite-sa@ce-cxmo-mom-dev-01.iam.gserviceaccount.com)" https://mom-regression-suite-test-5fdcrsjqlq-uc.a.run.app/trigger-suite/)
       if [ "200" != "$$RESPONSE" ]; then exit 1; fi

images: ['gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA']
timeout: 1000s
